project:
  type: book
  output-dir: docs

book:
  title: "CASA0023  Learning Diary"
  description: "My Journey to Remote Sensing Cities and Environments"
  author: "Yuxi Zheng"
  date: "2/3/2023"

  navbar:
    logo: logo.png
    collapse: true
    collapse-below: lg
    background: primary
    style: sticky
    text-color: white
    search: true
    right:
      - icon: github

  sidebar:
    title: "CASA0023"
    style: docked
    background: primary
    text-color: white
    divider: true
    nav-accent: secondary
    nav-text-color: white
    reader-mode: true
    
  repo-url: https://github.com/thea89123/casa0023.git

  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    
  reader-mode: true
bibliography: references.bib
    

format:
  html:
    theme: minty
    code-link: true
    css: styles.css
    title-block-banner: "banner.png"
    title-block-style: default
    title-block-categories: false
    title-block-banner-color: "body"
    

  pdf:
    documentclass: scrbook


   
